version: '3.0'
volumes:
  node10modules: null
  node10tmp: null
  node14modules: null
  node14tmp: null
services:
  node10:
    image: node:10.21.0-jessie-slim
    working_dir: /package
    command: sh -c  "yarn --frozen-lockfile && yarn test"
    volumes:
      - ./:/package
      - node10modules:/package/node_modules
      - node10tmp:/package/.tmp
      
  node14:
    image: node:14-stretch-slim
    working_dir: /package
    command: sh -c  "yarn --frozen-lockfile && yarn test"
    volumes:
      - ./:/package
      - node14modules:/package/node_modules
      - node14tmp:/package/.tmp
